services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./docker/cloudflared:/etc/cloudflared:ro
    restart: always
    network_mode: host
  tunnel2:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./docker/cloudflared:/etc/cloudflared:ro
    restart: always
    network_mode: host
