spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g3
    username: postgres
    password: admin
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER:}
    password: ${MAIL_PASS:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 60000
          timeout: 60000
          writetimeout: 60000
        transport:
          protocol: smtp
        debug: false
    default-encoding: UTF-8
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 60MB
    max-swallow-size: 60MB

app:
  geocoding:
    base-url: https://nominatim.openstreetmap.org/search
    user-agent: g3-geocoder
    enabled: true
  storage:
    beneficiarios: storage/beneficiarios
    fotos-eventos: storage/fotos-eventos
  email:
    habilitado: ${APP_EMAIL_HABILITADO:true}
    remetente: ${APP_EMAIL_REMETENTE:}
    nome-remetente: ${APP_EMAIL_NOME:HTA Sistemas}
